uploads = []
generated = []

[[outputs]]
id = "lX3YL6YcNkSTiclu9Sy0O"
uri = "file://artifacts/acams-prep-video/public/images/finance-bg.jpg"
type = "image"
title = "dark blue abstract financial data network nodes modern professional"

[[outputs]]
id = "vBKllWpNwxgz92UEpblim"
uri = "file://docs/requirements-document.md"
type = "text"
title = "Requirements Document"

[[outputs]]
id = "4uICibyZtxp5LPyncsqQ0"
uri = "file://docs/technical-document.md"
type = "text"
title = "Technical Document"

[[outputs]]
id = "QdRuzEPpx3pVXbxkCmL6H"
uri = "file://docs/user-guide.md"
type = "text"
title = "User Guide"
